### PR TITLE
Fixes bug related to token validation

### LINKED ISSUE #23: Bug: As a user, if I enter invalid characters in the token input, the field gets overrun by backslashes.
Once an invalid character is entered into the token input field, backslashes are entered into the input field with every key press (even `backspace`).
If a `/` is entered, the app crashes entirely.

image

AC:
- [ ] Invalid characters should trigger a warning of an invalid token
- [ ] The submit button is disabled until the input is valid
- [ ] Token name can be case insensitive

### PR DESCRIPTION
**Pull request by CorinaMurg**
_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._

## Description

We removed the `sanitizeInput` function from the `Home` component and introduced the following safeguards:
- disabling the `Join` button while the input is invalid
- testing for a three-word token
- testing for and alerting users of non-letter characters
- removing extra spaces from user inputs
- making inputs case-insensitive
- allowing calls to Firebase only if the token is valid

Because "/" is used by Firestore as a path separator, it caused the app to crash when entered into the token field. By checking  a token's validity before passing it to the `useShoppingListData` we now prevent communication with the database when "/" is used.

While the button is inactive, we allow users to press the `Enter` key and receive an error message. This feature should enhance accessibility for screen reader users.

## Related Issue

closes #23

## Acceptance Criteria

- [ ] Invalid characters trigger a warning of an invalid token
- [ ] The submit button is disabled until the input is valid
- [ ] Token name can be case insensitive

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|  ✓  | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|  ✓  | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before

image

### After

image

## Testing Steps / QA Criteria

To pull our branch locally, run `git pull origin at-cm-issue27BugFix`
Next, run `git checkout at-cm-issue27BugFix`
Launch the app with `npm start`

### Ways to test:
- When landing on the `Home` page, the `Join` button should be inactive.
- Enter any non-letter character and an error message should appear on the screen for 7 seconds.
- The `Join` button becomes active as the user starts typing the 3rd word, but changes to disabled again if a non-letter character is entered or more words are added
- Press the `Enter` key while the button is disabled. It should trigger an error message.
- Testing with ` my    test  LIST  ` (notice the extra spaces!) should open the default `my test list`.

### Please note: 
Extra spaces between the words or at the beginning or end of the token input are dealt with by 
the `handleInputChange` function and will not trigger an error message.

### CODE REVIEW

File: src/views/Home.jsx [hunk 1]
```diff
@@ -34,19 +34,40 @@ export function Home({ setListToken }) {
...
+
+	// This function resets the token input and keeps focus on the input field
+	const clearTokenInput = () => {
+		setTokenInput('');
+		tokenInputRef.current.focus();
+	}
+
+	
+	// trim spaces at both ends of the token; keep only one space between words; turn all letters to lower case
+	const token = tokenInput.trim().replace(/\s+/g, ' ').toLowerCase();
```
Comment (shangguanwang) [inline src/views/Home.jsx:64]: nice regex combo!

File: src/views/Home.jsx [hunk 2]
```diff
@@ -56,44 +77,53 @@ export function Home({ setListToken }) {
...
-		const sanitizedInput = sanitizeInput(event.target.value);
-		setTokenInput(sanitizedInput);
-	};
-	  
-
-	// This function resets the token input and keeps focus on the input field
-	const clearTokenInput = () => {
-		setTokenInput('');
-		tokenInputRef.current.focus();
+	const handleEnterKey = (event) => {
```
Comment (shangguanwang) [inline src/views/Home.jsx:83]: Great choice here using the `onKeyDown` attribute!

**Review by rdpfeifle — APPROVED** [review]
Thank you for explaining how to test each part of it so well; it was very useful for me. Every small feature you added worked, from the inactive button to detecting that `my test list` exists in the Firestore even by adding multiple spaces and capitalization. Great job! 👏🏼🥳

File: src/views/Home.jsx [hunk 3]
```diff
@@ -56,44 +77,53 @@ export function Home({ setListToken }) {
...
+		if (event.key === "Enter") {
+			event.preventDefault()
+			if (!isTokenValid) {
+				setErrorMessage('A token must contain exactly three words separated by a space.')
```
Comment (shangguanwang) [inline src/views/Home.jsx:86]: non-critical suggestion: I love how you separate the errorMessage for different scenarios, since setErrorMessage and setTimeout was used multiple times, maybe you can create a reusable function
```
const displayErrorMessage = (message, durationMs = 7000) => {
  setErrorMessage(message);

  setTimeout(() => {
    setErrorMessage("");
  }, durationMs);
};
```
then call the function `displayErrorMessage('A token must contain exactly three words separated by a space.');`

**Review by shangguanwang — APPROVED** [review]
Very well-rounded approach to ensure the user input is formatted correctly and I love how you included all the possible error scenarios. Great job spotting the bug in Firebase!!

File: src/views/Home.jsx (hunk 3 above)
Comment (CorinaMurg) [reply src/views/Home.jsx:86]: Oh, this is a great suggestion! Thank you!

Comment (cafloyd) [reply src/views/Home.jsx:86]: Love when we DRY up code like this!

File: src/views/Home.jsx [hunk 4]
```diff
@@ -42,7 +42,7 @@ export function Home({ setListToken }) {
 		setIsTokenValid(tokenWords.length === 3);
 
 		// test for all non-letter characters; 
-		// please note: it does not work for '/'. see useShoppingListData function in firestore.js
+		// please note: it does not work for '/', but do not panic! see useShoppingListData function in firestore.js for solution
```
Comment (cafloyd) [inline src/views/Home.jsx]: ❤️

File: src/views/Home.jsx [hunk 5]
```diff
@@ -56,44 +73,53 @@ export function Home({ setListToken }) {
...
 		<div className="Home">
 			<Button label="Create New List" onClick={createNewList} />
 			<p>-or-</p>
-			<p>Join an existing shopping list by entering a three word token.</p>
+			<p>Join an existing shopping list.</p>
 
 			<form onSubmit={submitTokenInput}>
 				<label htmlFor="tokenInput">
-				Enter token:
+				Enter a 3-word token (example: "word word word"):
```
Comment (cafloyd) [inline src/views/Home.jsx:105]: This is a helpful update!

File: src/views/Home.jsx [hunk 6]
```diff
@@ -56,44 +73,53 @@ export function Home({ setListToken }) {
...
 				<br />
 					<input
 						type="text"
 						name="tokenInput"
 						id="tokenInput"
 						value={tokenInput}
 						onChange={handleInputChange}
+						onKeyDown={handleEnterKey}
```
Comment (cafloyd) [inline src/views/Home.jsx:113]: Nice!

**Review by cafloyd — APPROVED** [review]
Really nice job, team - y'all went above and beyond with fixing this bug! I agree with Raquel, the testing instructions on this PR were excellent. I also appreciate the thoughtful use of comments in the code. Great work!

File: src/api/firebase.js [hunk 7]
```diff
@@ -17,7 +17,9 @@ export function useShoppingListData(listId) {
 	const [data, setData] = useState(initialState);
 
 	useEffect(() => {
-		if (!listId) return;
+		// "/" is used by Firestore as a path separator and causes the app to crash when enter into the token field
+		// this restriction prevents communication with the database when "/" is used
+		if (!listId || listId.includes("/")) return;
```
Comment (mentalcaries) [inline src/api/firebase.js:22]: Good catch with this!

File: src/views/Home.jsx [hunk 8]
```diff
@@ -34,19 +34,40 @@ export function Home({ setListToken }) {
...
-		
-		if(tokenInput.trim() === "") {
-			setErrorMessage("Please, enter 3-word token.");
+		// test for a three-word token
+		const tokenWords = tokenInput.split(' ').filter(word => word !== '');
+		setIsTokenValid(tokenWords.length === 3);
+
+		// test for all non-letter characters; 
+		// please note: it does not work for '/', but do not panic! see useShoppingListData function in firestore.js for solution
+		if (/[^a-zA-Z\s]/.test(tokenInput)) {
```
Comment (mentalcaries) [inline src/views/Home.jsx:45]: Love all these checks and error messages to guide the user!

**Review by mentalcaries — APPROVED** [review]
Nice work on fixing this bug!!

File: src/api/firebase.js (hunk 7 above)
Comment (CorinaMurg) [reply src/api/firebase.js:22]: We think we might have now a more optimal solution.
Right now, the validation process impacts the UI (disables the button and triggers error messages) but it does not prevent `useShoppingListData` from contacting Firestore to check whether the token exists as a collection.
The function returns immediately only if the listId is falsy or the “/” is used:
`if (!listId || listId.includes("/")) return;`
We could turn any invalid input into a falsy value by conditionally supplying the token to the function inside the Home component, like this:
`const sharedListData = useShoppingListData(isTokenValid ? token : null);`
(This also eliminates the need for the `listId.includes("/")` condition).

Comment (mentalcaries) [reply src/api/firebase.js:22]: Definitely seems more optimal to check for valid data before making the API call. Good job!
